### ISSUE TITLE
Gases - mixed types available?

### ISSUE THREAD

**Issue by joshtate** [LBNL-ETA/pyWinCalc#3]
Right now there seem to be only 4 types of gases available:  Air, Argon, Krypton, and Xenon.  Is there a way to use the mixed types available in the IGDB (e.g. ID 9: Air (10%) / Argon (90%) Mix)?

**Comment by StephenCzarnecki** [comment]
Sorry for the delayed response.  The short answer is not currently but hopefully soon.

I can't make any promises since I am just the dev working on the project and not the project manager.   But after some time working on other unrelated projects I am now working on one to integrate the underlying libraries used by pyWinCalc into our WINDOW application.  And I believe will require not only being able to use mixed types but also being able to create arbitrary gases as well as other functionality.

Generally once the underlying libraries have the functionality exposing them to Python is the easy bit.  

The integration work is currently scheduled to be completed by the end of September.  Depending on how the rest of the integration work goes I will keep an eye out for a good time and way to expose the additional gas functionality as it becomes available.  If there doesn't seem to be a way to do it during the rest of the work then hopefully shortly after it is completed I can see about exposing not only the gases but the other new functionality to python as well.

I will try to keep you updated about any progress regarding gases in this issue.

Thanks again for your interest.
