### ISSUE TITLE
pyWinCalc packaged with pyinstaller gives internal error

### ISSUE THREAD

**Issue by RebeccaPowles** [LBNL-ETA/pyWinCalc#53]
Steps to reproduce:
pywincalc v. 3.6.9
all examples run OK at command line

package minimum_example.py with pyinstaller:

pyinstaller --name minimum_example ./examples/minimum_example.py

you will need to run the executable from examples so that it can see "products/CLEAR_3.DAT"

When executing, the following error is raised by the call to u():
IndexError: invalid map<K, T> key

I have verified that the module is loaded (the parse call works) and that the layer object is OK (you can print the layer thickness for example).

This did at some point work and I am not sure how to proceed - any clues would be gratefully received! 

Regards,
Rebecca

**Comment by StephenCzarnecki** [comment]
Hi Rebecca

The good news is I am able to reproduce the issue.  The less good news is I am not terribly familiar with pyinstaller so I am not immediately sure why it might not be working when running the examples using the python interpreter does.

As you note since other functions seem to be working it seems like it is not an issue with pyinstaller in general.  So my first inclination is to try to tinker with the C++ layer a bit to see if I can get it to give some more information about what is going on in the u() call that causes that particular error.  Hopefully that will be able to shed some light on what is going on.

I'll let you know how things progress.

**Comment by StephenCzarnecki** [comment]
@RebeccaPowles I think I have figured out the issue and a solution.

The problem appears to be that by default pyinstaller does not include non-python files in the build.  pywincalc now bundles the default optical standards files directly but since they are not python files pyinstaller is not including them.  The issue you are seeing is that when part of the U-value calculation routine looks for the thermal IR method it cannot find it and gives the invalid map key error.  Not the most informative of errors to be sure.  Hopefully I can take a pass at making them a bit more useful in the future.

In any event there seem to be a couple different ways of getting the optical standards files included.  One way is to edit the .spec file to collect the pywincalc data files and use them.  I've included an example attached to this issue named minimum_example.spec.txt (because github won't allow .spec filetypes).  The main change is adding the `datas = collect_data_files('pywincalc')` bit and then passing that to the `Analysis` object.

[minimum_example.spec.txt](https://github.com/user-attachments/files/17819889/minimum_example.spec.txt)

Then you can build from the spec file like

`pyinstaller minimum_example.spec`

A second way is to find where the installed pywincalc package keeps the files and pass that to pyinstaller in the `add-data` parameter.  In my case I installed pywincalc in a venv named `env` under `c:\github_2\pyWinCalc`.  If I run pyinstaller like this

`(env) C:\github_2\pyWinCalc>pyinstaller -F --name minimum_example ./examples/minimum_example.py --add-data "C:\\github_2\\pyWinCalc\\env\\Lib\\site-packages\\pywincalc\\standards\\;pywincalc\\standards"`

that also seems to bundle the optical standards files with the executable.  Note the ";" in the string passed to --add-data.

Let me know if either approach fixes the pyinstaller problem or if you are still having issues.

**Comment by RebeccaPowles** [comment]
You are my absolute hero!  I have been cracking my head on this for days...
I can confirm both methods work perfectly.
Did you know I am the original author of those standard files?  They have come back to haunt me!
Thanks so much again

**Comment by StephenCzarnecki** [comment]
Glad it is working now and I did not know you were the original author.

Sorry about the bother but so far at least this is the best way we've come up with to deal with the standards files.  Previously they were not included in the python module which made their use more explicit.  But that came at the cost of the user always having to deal with knowing where they were and which ones to use.  

So we changed to bundling them with the python module.  That made it so we could default to the same NFRC standard file that WINDOW uses while still providing the other standards files and made it so the users didn't have to keep track of where the standards files were on their filesystem.  And for the most part that seems like an improvement in usability except for what you just ran into.

I think part of the issue is that the C++ exceptions are not necessarily that informative.  I've tried to add more useful exceptions in other parts of the code so it is probably a good idea to add some more verbose error messages.  Although if I could get a stack trace to propagate to the python level that would help diagnosing issues like this.

e.g. if instead of just `IndexError: invalid map<K, T> key` you got something like

```
IndexError: invalid map<K, T> key
auto ir_method = standard.methods.at("THERMAL IR");
etc...
```

that would help at least narrow down where to look.

So I'll try to look into to what degree that may be possible too.

Also as far as I know you are the first to try building pywincalc into an exe so if you run into any other issues with that (or anything else) just let us know.
